### ISSUE TITLE
add londonjs 

### ISSUE THREAD

**Issue by iancrowther** [lnug/related-meetups#11]
https://twitter.com/london_JS

**Comment by ifraixedes** [comment]
I don't know if you have seen that this group is already [there](https://github.com/lnug/related-meetups#london-javascript-community) but with the name that they have in Meetup; I could match it because I added it :smiley: so it was easy to be identified by me.

In case that we would like to add more information, which one should we add? twitter, ...?

**Comment by iancrowther** [comment]
@ifraixedes - just want it to be consistant really

**Comment by ifraixedes** [comment]
@iancrowther What do you think about the changes under #12?

**Comment by iancrowther** [comment]
+1 ty
